__author__ = "Jeremy Lainé"
__email__ = "jeremy.laine@m4x.org"
__license__ = "BSD"
__summary__ = "Python wrapper around the libsrtp library"
__title__ = "pylibsrtp"
__uri__ = "https://github.com/aiortc/pylibsrtp"
__version__ = "0.7.1"
