#!/bin/sh

set -e

if [ ! -e "libsrtp" ]; then
    git clone https://github.com/cisco/libsrtp/
fi
cd libsrtp
git checkout v2.1.0

if [ -e "Makefile" ]; then
    make distclean
fi
rm -rf /tmp/libsrtp

./configure --prefix=/tmp/libsrtp
make
make install
