#!/bin/sh

set -e

if [ -e "libsrtp" ]; then
    make -C libsrtp distclean
else
    git clone https://github.com/cisco/libsrtp/
fi
rm -rf libsrtp/local

cd libsrtp
./configure --prefix=$PWD/local
make
make install
