#!/bin/sh

set -e

destdir=/tmp/libsrtp

for d in libsrtp $destdir; do
    if [ -e $d ]; then
        rm -rf $d
    fi
done

git clone https://github.com/cisco/libsrtp/
cd libsrtp
git checkout -qf v2.1.0

./configure --prefix=$destdir
make
make install
