#!/bin/sh

set -e

if [ "$BUILD" = "sdist" ]; then
    python3 setup.py sdist
    if [ -n "$TRAVIS_TAG" ]; then
        twine upload --skip-existing dist/*
    fi
elif [ "$BUILD" = "wheel" ]; then
    cibuildwheel --output-dir wheelhouse
    if [ -n "$TRAVIS_TAG" ]; then
        twine upload --skip-existing wheelhouse/*
    fi
fi
