#!/bin/sh

set -e

if [ "$BUILD" = "lint" ]; then
    flake8 pylibsrtp
elif [ "$BUILD" = "sdist" ]; then
    python3 setup.py sdist
    if [ -n "$TRAVIS_TAG" ]; then
        pip3 install twine
        python3 -m twine upload --skip-existing dist/*
    fi
elif [ "$BUILD" = "wheel" ]; then
    cibuildwheel --output-dir wheelhouse
    if [ -n "$TRAVIS_TAG" ]; then
        pip3 install twine
        python3 -m twine upload --skip-existing wheelhouse/*
    fi
else
    coverage run setup.py test
    curl -s https://codecov.io/bash | bash
fi
